#
# Copyright (c) 2021 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for booting Yocto linux on FVP-R
#

# FVP-R BL1
expect_string+=('i;Booting Trusted Firmware')
expect_string+=('i;BL1: Booting BL33')

# Uboot
expect_string+=('i;U-Boot')

# Yocto
expect_string+=('i;Booting Linux on physical CPU')
expect_string+=('i;fvp-baser-aemv8r64 login:;;;root\n')
expect_string+=('i;#')
