#
# Copyright (c) 2021 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for Trusted Firmware + U-Boot + Linux boot process with
# OpenEmbedded rootfs in /dev/vda2
#

# Trusted Firmware boot section
source $ci_root/lava-expect/trusted-firmware.inc

# Linux kernel boot section
source $ci_root/lava-expect/linux.inc

# OpenEmbedded filesystem section
source $ci_root/lava-expect/openembedded.inc
