#
# Copyright (c) 2019-2023 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for Trusted Firmware Test Framework
#

source [file join [file dirname [info script]] handle-arguments.inc]

expect_string "Unhandled External Abort received"
expect_string "Unhandled Exception from EL2"

source [file join [file dirname [info script]] exception_regs.inc]
expect_string "x30"
