#
# Copyright (c) 2023, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for Trusted Firmware Test Framework
#

expect_string "x0"
expect_string "x1"
expect_string "x2"
expect_string "x3"
expect_string "x4"
expect_string "x5"
expect_string "x6"
expect_string "x7"
expect_string "x8"
expect_string "x9"
expect_string "x10"
expect_string "x11"
expect_string "x12"
expect_string "x13"
expect_string "x14"
expect_string "x15"
expect_string "x16"
expect_string "x17"
expect_string "x18"
expect_string "x19"
expect_string "x20"
expect_string "x21"
expect_string "x22"
expect_string "x23"
expect_string "x24"
expect_string "x25"
expect_string "x26"
expect_string "x27"
expect_string "x28"
expect_string "x29"
