
#
# Copyright (c) 2022 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for Linux boot process with RAM Disk for sgi platform
#
# Refer to handle-arguments.inc for the list of parameters.
#

source [file join [file dirname [info script]] handle-arguments.inc]

# Linux kernel boot section
source [file join [file dirname [info script]] linux.inc]

# Busybox filesystem section
source [file join [file dirname [info script]] busybox.inc]

exit_uart -1
