#
# Copyright (c) 2020-2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

source [file join [file dirname [info script]] handle-arguments.inc]

expect {
	"Please press Enter to activate this console." {
		message "Linux PVM booted"
		send "\r"
	}
}

expect {
	"/ # " {
		send "insmod hafnium.ko\n"
	}
}

expect {
	"Hafnium successfully loaded with 1 VMs:" {
		message "Hafnium driver started"
	}
}

exit_uart 0
