#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for Trusted Firmware Test Framework
#

source [file join [file dirname [info script]] handle-arguments.inc]

expect_string "Booting trusted firmware test framework" "Starting TFTF"
expect {
        timeout {
		puts "<<Timeout expected - Success>>"
                exit_uart 0
        }
}

exit_uart -1
