#
# Copyright (c) 2020, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for Trusted Firmware Test Framework
#

source [file join [file dirname [info script]] handle-arguments.inc]

expect_string "Translation tables are now read-only at EL3."
expect {
        timeout {
		puts "<<Timeout expected - Success>>"
                exit_uart 0
        }
}

exit_uart -1
