#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

test_setup() {
	# Parallel builds are broken for this config; so choose serial.
	echo "Choosing serial build."
	set_hook_var "make_j" "1"
}

pre_tf_build() {
	pushd "$workspace"

	if [ ! -d "mv-ddr-marvell" ]; then
		# Archive from mv-ddr-marvell 14.0.0 release
		saveas="mv-ddr-marvell.tar.gz" \
			url="$tfa_downloads/mv-ddr-marvell/mv-ddr-marvell-fae3f6c98230ae51a78e248af5de96fac97a8fca.tar.gz" \
			fetch_file

		tar -xzf "mv-ddr-marvell.tar.gz"
	fi

	echo "Set MV_DDR_PATH to $workspace/mv-ddr-marvell"
	set_hook_var "MV_DDR_PATH" "$workspace/mv-ddr-marvell"

	popd "$workspace"
}
