#!/usr/bin/env bash
#
# Copyright (c) 2019, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

test_setup() {
	# Coverity scan only need to run on debug builds
	echo "Building only in DEBUG mode."
	set_hook_var "bin_mode" "debug"
}

pre_tf_build() {
	wrapper="coverity" setup_tf_build_wrapper
}
