#!/usr/bin/env bash
#
# Copyright (c) 2019, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

fetch_tf_resource() {
	url="$sgi_prebuilts/mcp-rom.bin" fetch_file
	url="$sgi_prebuilts/scp-ram.bin" fetch_file
	url="$sgi_prebuilts/scp-rom.bin" fetch_file


	archive_file "mcp-rom.bin"
	archive_file "scp-ram.bin"
	archive_file "scp-rom.bin"
}

post_fetch_tf_resource() {
	model="css-rde1edge" \
	model_version="11.9" \
	model_build="41" \
	gen_model_params
	set_run_env "ports_script" "$ci_root/model/css-sgi575-ports.awk"
	set_run_env "num_uarts" "2"
	uart="0" set_expect_variable "num_cpus" "32"
}
