#!/bin/bash
#
# Copyright (c) 2019, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

pre_tf_build() {
	# Build sptool for this config
	targets="all fiptool sptool" set_tf_build_targets
}

pre_tftf_build() {
	# Build TFTF, Cactus and Ivy for this config
	targets="tftf cactus ivy" set_tftf_build_targets
}

post_tf_build() {
	# Build the Secure Partition package
	trusted_firmware/tools/sptool/sptool				\
		-o "$archive/bl32.bin"					\
		-i "$archive/cactus.bin":"$archive/cactus.dtb"		\
		-i "$archive/ivy.bin":"$archive/ivy.dtb"
}

post_fetch_tf_resource() {
	uart="2" file="cactus.exp" track_expect
	uart="3" file="ivy.exp" track_expect
}
