#!/usr/bin/env bash
#
# Copyright (c) 2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
	local model="tc2"

	model="tc2" \
	model_version="11.18" \
	model_build="17" \
	gen_model_params
	set_run_env "ports_script" "$ci_root/model/tc-ports.awk"
	set_run_env "num_uarts" "3"
	uart="1" set_expect_variable "num_cpus" "8"
	model="$model" gen_fvp_yaml
}
