#!/usr/bin/env bash
#
# Copyright (c) 2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job() {
	local model="cortex-a78cx4"

	uart="0" set_expect_variable "num_cpus" "4"

	model="$model" \
	cluster_0_num_cores="4" \
	use_pchannel_for_threads="1" \
	gen_model_params
	model="$model" gen_fvp_yaml
}
