#!/usr/bin/env bash
#
# Copyright (c) 2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
        local model="neoverse_n2"

	model="$model" \
	cache_state_modelled="0" \
	gen_model_params
	uart="0" set_expect_variable "num_cpus" "4"
	model="$model" gen_fvp_yaml
}
