#!/usr/bin/env bash
#
# Copyright (c) 2020, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
	model="neoverse_e1x4" \
	cache_state_modelled="1" \
	data_instance="cluster0.cpu0.thread0" \
		gen_model_params
	uart="0" set_expect_variable "num_cpus" "8"

	model="neoverse_e1x4" \
	model_bin="FVP_Base_Neoverse-E1x4" \
	       gen_fvp_yaml
}
