#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
	model="cortex-a55x4-a75x4" \
	cache_state_modelled="0" \
	gen_model_params

	model="cortex-a55x4-a75x4" \
	model_bin="FVP_Base_Cortex-A55x4+Cortex-A75x4" \
	       gen_fvp_yaml
}
