#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
	local model="cortex-a35x4"
	model="$model" gen_model_params
	uart="0" set_expect_variable "num_cpus" "4"

	model="$model" \
	model_bin="FVP_Base_Cortex-A35x4" \
	gen_fvp_yaml
}
