#!/usr/bin/env bash
#
# Copyright (c) 2019-2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job() {
	local model="cortex-a55x4-a76x2"

	uart="0" set_expect_variable "num_cpus" "6"

	model="$model" \
	data_instance="cluster0.subcluster0.cpu0" \
	use_pchannel_for_threads="1" \
	gen_model_params
	model="$model" gen_fvp_yaml
}
