#!/usr/bin/env bash
#
# Copyright (c) 2019-2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

# data_instance must be set to cluster0.cpu0.thread0 because the model does not accept --data
# parameter on the default cluster0.cpu0 instance.

generate_lava_job() {
	local model="cortex-a65x4"

	uart="0" set_expect_variable "num_cpus" "8"

	model="$model" \
	data_instance="cluster0.cpu0.thread0" \
	cluster_0_num_cores="4" \
	gen_model_params
	model="$model" gen_fvp_yaml
}
