#!/usr/bin/env bash
#
# Copyright (c) 2019-2021, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
        local model="tc0"

	model="$model" gen_model_params
	set_run_env "ports_script" "$ci_root/model/tc-ports.awk"
	set_run_env "num_uarts" "2"
	uart="1" set_expect_variable "num_cpus" "8"
	model="$model" gen_fvp_yaml
}
