#!/usr/bin/env bash

post_fetch_tf_resource() {
        local model="cortex-x2"

	model="$model" \
	cache_state_modelled="0" \
	gen_model_params
	uart="0" set_expect_variable "num_cpus" "4"
	model="$model" gen_fvp_yaml
}
