#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
	model="cortex-a57x4-a53x4" gen_model_params

	model="cortex-a57x4-a53x4" \
	model_bin="FVP_Base_Cortex-A57x4-A53x4" \
	       gen_fvp_yaml
}
