#!/usr/bin/env bash
#
# Copyright (c) 2020, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_tf_build() {
	url="$project_filer/ci-files/spm-10-23-2020/secure_hafnium.bin" fetch_file

	archive_file "secure_hafnium.bin"

	build_fip BL33="$archive/tftf.bin" BL32="$archive/secure_hafnium.bin"
}

post_fetch_tf_resource() {
	model="base-aemv8a" \
	arch_version="8.4" \
		gen_model_params
}

fetch_tf_resource() {
	# Expect scripts
	uart="0" file="tftf.exp" track_expect
	uart="2" file="spm-uart2.exp" track_expect
}
