#!/usr/bin/env bash
#
# Copyright (c) 2021-2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job() {
	local model="cortex-a710"

	uart="0" set_expect_variable "num_cpus" "4"

	model="$model" cache_state_modelled="0" gen_model_params
	model="$model" gen_fvp_yaml
}
