#!/usr/bin/env bash
#
# Copyright (c) 2020, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
        local model="neoverse_e1x1"

	model="$model" \
	cache_state_modelled="1" \
	data_instance="cluster0.cpu0.thread0" \
		gen_model_params
	uart="0" set_expect_variable "num_cpus" "2"
	model="$model" gen_fvp_yaml
}
