#!/usr/bin/env bash
#
# Copyright (c) 2019-2022 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

fetch_tf_resource() {
	uart="0" timeout="1200" file="tftf.exp" track_expect
	uart="1" file="hold_uart.exp" track_expect

	payload_type="tftf" gen_fvp_yaml_template
}
