#!/usr/bin/env bash
#
# Copyright (c) 2019-2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job() {
	local model="cortex-a72x4-a53x4"

	model="$model" gen_model_params
	model="$model" gen_fvp_yaml
}
