#!/usr/bin/env bash
#
# Copyright (c) 2021 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
fetch_tf_resource() {
	uefi_ci_bin_url="$morello_prebuilts/uefi.bin" get_uefi_bin

	# Hold terminal_uart_aon (SCP terminal)
	uart="2" file="hold_uart.exp" track_expect
}

post_fetch_tf_resource() {
	local model="morello"

	model="morello" \
	model_version="0.10" \
	model_build="481" \
	gen_model_params
	set_run_env "ports_script" "$ci_root/model/morello-ports.awk"
	set_run_env "num_uarts" "3"

	uart="1" set_expect_variable ""skip_early_boot_msgs"" "1"
	uart="1" set_expect_variable "num_cpus" "4"

	model="$model" gen_fvp_yaml
}
