#!/bin/bash
#
# Copyright (c) 2019, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

fetch_tf_resource() {
	kernel_type="fvp-aarch32-zimage" get_kernel
	initrd_type="aarch32-ramdisk" get_initrd
	uart="0" file="linux-rd-busybox-aarch32.exp" track_expect
}
