#!/usr/bin/env bash
#
# Copyright (c) 2021-2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job() {
	local model="tc1"

	uart="1" set_expect_variable "num_cpus" "8"

	set_run_env "ports_script" "$ci_root/model/tc-ports.awk"
	set_run_env "num_uarts" "2"

	model="$model" gen_model_params
	model="$model" gen_fvp_yaml
}
