#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
	model="cortex-a57x1-a53x1" gen_model_params
        uart="0" set_expect_variable "num_cpus" "2"

	model="cortex-a57x1-a53x1" \
	model_bin="FVP_Base_Cortex-A57x1-A53x1" \
	       gen_fvp_yaml
}
