#!/usr/bin/env bash
#
# Copyright (c) 2019-2020, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

fetch_tf_resource() {
	# Use SCP binary from SCP build if it exists, or fetch pre-built ones.
	if [ ! -f "$archive/scp_romfw.bin" ]; then
		url="$scp_prebuilts/scp_romfw.bin" fetch_file
		archive_file "scp_romfw.bin"
	fi

	# Hold scp terminal_s0
	uart="0" file="hold_uart.exp" track_expect
}

post_fetch_tf_resource() {
        local model="tc0"

	model="$model" gen_model_params
	set_run_env "ports_script" "$ci_root/model/tc0-ports.awk"
	set_run_env "num_uarts" "2"
	uart="1" set_expect_variable "num_cpus" "4"
	model="$model" gen_fvp_yaml
}
