#!/usr/bin/env bash
#
# Copyright (c) 2021-2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job() {
	local model="morello"

	uart="1" set_expect_variable "skip_early_boot_msgs" "1"
	uart="1" set_expect_variable "num_cpus" "4"

	# Hold terminal_uart_aon (SCP terminal)
	uart="2" file="hold_uart.exp" track_expect

	set_run_env "ports_script" "$ci_root/model/morello-ports.awk"
	set_run_env "num_uarts" "3"

	model="morello" \
		model_build="33" \
		model_flavour="Linux64_GCC-6.4" \
		model_version="0.11" \
		gen_model_params

	model="$model" gen_fvp_yaml
}
