#!/usr/bin/env bash

generate_lava_job() {
	local model="cortex-a78x4"

	uart="0" set_expect_variable "num_cpus" "4"

	model="$model" cache_state_modelled="0" gen_model_params
	model="$model" gen_fvp_yaml
}
