#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_tf_build() {
	fvp_romlib_runtime
}

post_tf_archive() {
	fvp_romlib_cleanup
}
