#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_fetch_tf_resource() {
        local model="cortex-a55x4-a75x4"

	model="$model" cache_state_modelled="0" gen_model_params
	model="$model"  gen_fvp_yaml
}
