#!/usr/bin/env bash
#
# Copyright (c) 2020, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_tf_build() {
	build_fip BL33="$archive/tftf.bin" BL32="$archive/secure_hafnium.bin"
}

fetch_tf_resource() {
	# Expect scripts
	uart="0" file="tftf.exp" track_expect
	uart="2" file="spm-uart2.exp" track_expect
}

post_fetch_tf_resource() {
        local model="base-aemv8a"

	model="$model" arch_version="8.4" gen_model_params
	model="$model" gen_fvp_yaml
}
