#!/usr/bin/env bash
#
# Copyright (c) 2020-2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job() {
	local model="neoverse_e1x2"

	uart="0" set_expect_variable "num_cpus" "4"

	model="$model" \
	cluster_0_num_cores="2" \
	data_instance="cluster0.cpu0.thread0" \
	gen_model_params

	model="$model" gen_fvp_yaml
}
