#!/usr/bin/env bash

post_fetch_tf_resource() {
	model="cortex-a78x4" \
	cache_state_modelled="0" \
	gen_model_params
	uart="0" set_expect_variable "num_cpus" "4"

	model="cortex-a78x4" \
	model_bin="FVP_Base_Cortex-A78x4" \
	       gen_fvp_yaml
}
