#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

fetch_tf_resource() {
	# Fetch the pre-built SCP/MCP binaries if they haven't been built
	if [ ! -f "$archive/mcp_rom.bin" ]; then
		url="$sgi_prebuilts/mcp_rom.bin" fetch_file
		archive_file "mcp_rom.bin"
	fi
	if [ ! -f "$archive/scp_ram.bin" ]; then
		url="$sgi_prebuilts/scp_ram.bin" fetch_file
		archive_file "scp_ram.bin"
	fi
	if [ ! -f "$archive/scp_rom.bin" ]; then
		url="$sgi_prebuilts/scp_rom.bin" fetch_file
		archive_file "scp_rom.bin"
	fi

	url="$tfa_downloads/SGI-575_cmn600.yml" fetch_file
	archive_file "SGI-575_cmn600.yml"

	# Hold terminal_uart_aon
	uart="2" file="hold_uart.exp" track_expect
}

post_fetch_tf_resource() {
	model="css-sgi575" gen_model_params
	set_run_env "ports_script" "$ci_root/model/css-sgi575-ports.awk"
	set_run_env "num_uarts" "3"
}
