#!/usr/bin/env bash
#
# Copyright (c) 2020-2022, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job() {
	local model="neoverse_e1x4"

	uart="0" set_expect_variable "num_cpus" "8"

	model="$model" \
		cache_state_modelled="1" \
		data_instance="cluster0.cpu0.thread0" \
		gen_model_params

	model="$model" gen_fvp_yaml
}
