#!/usr/bin/env bash
#
# Copyright (c) 2019, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_tf_build() {
	get_scp_bl2_bin
	build_fip BL33="$archive/tftf.bin" SCP_BL2="$archive/scp_bl2.bin"
}

post_fetch_tf_resource() {
	gen_recovery_image "$archive/bl1.bin" "$archive/fip.bin"
	payload_type="tftf" gen_juno_yaml
}
