#!/bin/bash
#
# Copyright (c) 2019, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_tf_archive() {
	config_file="$ci_root/tf_config/juno-aarch32-rst-to-sp-min" \
		juno_aarch32_runtime
}
