#!/usr/bin/env bash
#
# Copyright (c) 2022 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job_template(){
	payload_type="linux" target="qemu" gen_yaml_template
}

generate_lava_job(){
	local model="qemu-virt"

	model="$model" gen_model_params
	model="$model" gen_qemu_yaml
}
