#!/bin/bash
#
# Copyright (c) 2019, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

test_setup() {
	# Coverity scan only need to run on debug builds
	echo "Building only in DEBUG mode."
	set_hook_var "bin_mode" "debug"
}

pre_tf_build() {
	wrapper="scan_build" setup_tf_build_wrapper
}

post_tf_archive() {
	# Save scan-build reports to artefacts directory for offline analysis.
	find $workspace -name scan-build-reports -exec cp -rf {} $archive \; &> /dev/null
}
