FROM ${OS}:${OS_VER} as FVP

RUN apt-get update && \
    apt-get install --no-install-recommends --yes bc libatomic1 telnet libdbus-1-3 xterm && \
    rm -rf /var/cache/apt

FROM FVP

WORKDIR ${MODEL_DIR}

# Add the FVP model tarball
# NOTE: some tarballs contain an installer script others don't, so it may be the case
# that the ADD instruction do install the model under /opt/model
ADD ${MODEL}_${MODEL_VER}.tgz .

# Install packages and model
RUN ${MODEL_DIR}/${MODEL}.sh \
        --i-agree-to-the-contained-eula \
        --verbose \
        --destination ${MODEL_DIR}/${MODEL} && rm -f ${MODEL_DIR}/${MODEL}.sh || true
