#!/usr/bin/env bash
#
# Copyright (c) 2020, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

pre_tf_build() {
	python3 -m venv .venv && \
		. .venv/bin/activate && \
		python3 -m pip install -r "$tf_root/docs/requirements.txt"

	targets="doc" set_tf_build_targets
}
