#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

pre_tftf_build() {
	# Build only TFTF - avoid el3 payload since Hikey960's TF-A-Tests port
	# doesn't support it
	targets="tftf" set_tftf_build_targets
}
