#
# Copyright (c) 2023, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for Trusted Firmware Test Framework
#
expect_string+=("i;x0")
expect_string+=("i;x1")
expect_string+=("i;x2")
expect_string+=("i;x3")
expect_string+=("i;x4")
expect_string+=("i;x5")
expect_string+=("i;x6")
expect_string+=("i;x7")
expect_string+=("i;x8")
expect_string+=("i;x9")
expect_string+=("i;x10")
expect_string+=("i;x11")
expect_string+=("i;x12")
expect_string+=("i;x13")
expect_string+=("i;x14")
expect_string+=("i;x15")
expect_string+=("i;x16")
expect_string+=("i;x17")
expect_string+=("i;x18")
expect_string+=("i;x19")
expect_string+=("i;x20")
expect_string+=("i;x21")
expect_string+=("i;x22")
expect_string+=("i;x23")
expect_string+=("i;x24")
expect_string+=("i;x25")
expect_string+=("i;x26")
expect_string+=("i;x27")
expect_string+=("i;x28")
expect_string+=("i;x29")
