#
 # Copyright (c) 2022, Arm Limited. All rights reserved.
 #
 # SPDX-License-Identifier: BSD-3-Clause

expect_string+=('i;buildroot login:')
expect_string+=("i;;;;\n")
expect_string+=("i;;;;root")
expect_string+=("i;;;;\n")
expect_string+=('i;#')
expect_string+=("i;;;;\n")
expect_string+=("i;#;;;ioctl 255")
expect_string+=("i;;;;\n")
expect_string+=('i;Test: Echo Message to SP')
expect_string+=('i;Test: Message Relay vis SP to EL3 LSP.')
expect_string+=('i;Test: Memory Send.')
expect_string+=('i;Test: Memory Send in Fragments.')
expect_string+=('i;Test: Memory Lend.')
expect_string+=('i;Test: Memory Lend in Fragments.')
expect_string+=('i;Test: Memory Send with Multiple Endpoints.')
expect_string+=('i;Test: Memory Lend with Multiple Endpoints.')
expect_string+=('i;Test: Ensure Duplicate Memory Send Requests are Rejected.')
expect_string+=('i;Test: Ensure Duplicate Memory Lend Requests are Rejected.')
expect_string+=('i;Total Failures: 0')
